# On every push this script is executed
on:
  push:
    branches:
      - code 

name: Build and deploy GH Pages
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2
      # Build & deploy
      - name: Deploy to master branch
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: master
          # Provide personal access token
          TOKEN: ${{ secrets.TOKEN }}
